name: publish
on:
  workflow_dispatch:

jobs:
  build-tauri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-tags: true
          
      # - name: Make apt cache writable
      #   run: |
      #     sudo mkdir -p /var/cache/apt/archives
      #     sudo chown -R runner:runner /var/cache/apt/archives
      #     sudo chmod -R u+rwX /var/cache/apt/archives
          
      - name: Cache apt packages
        uses: actions/cache@v5
        with:
          path: ~/.apt-cache
          key: ${{ runner.os }}-${{ matrix.settings.target }}-apt-${{ hashFiles('.github/workflows/publish.yml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.settings.target }}-apt-

      - name: install dependencies (ubuntu only)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            -o dir::cache::archives="$HOME/.apt-cache" \ 
            libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
