name: publish
on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-tauri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-tags: true
          
      - name: Cache apt packages
        uses: actions/cache@v5
        with:
          path: ~/apt-cache
          key: ${{ runner.os }}-${{ matrix.settings.target }}-apt-${{ hashFiles('.github/workflows/publish.yml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.settings.target }}-apt-

      - name: install dependencies (ubuntu only)
        run: |
          mkdir -p ~/apt-cache && chmod -R a+rw ~/apt-cache
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends -o dir::cache::archives="$HOME/apt-cache" libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
          sudo chmod -R a+rw ~/apt-cache

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: packages/desktop/src-tauri
          shared-key: ${{ matrix.settings.target }}
      
      # Cache *cargo install* itself (separate concern)
      - uses: taiki-e/cache-cargo-install-action@v3
        with:
          tool: tauri-cli
          git: https://github.com/tauri-apps/tauri
          # BEST: pin a commit for stable caching & reproducibility
          # rev: <commit-sha>
          # If you must follow the branch:
          tag: feat/truly-portable-appimage
      
      - name: Show tauri-cli version
        run: cargo tauri --version
  